# Generated by Django 5.0.3 on 2024-03-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='requers_delivery',
            new_name='requires_delivery',
        ),
    ]
