# Generated by Django 5.0.3 on 2024-03-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_quantite_products_quantity'),
        ('orders', '0002_rename_requers_delivery_order_requires_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ORderItems',
            new_name='OrderItem',
        ),
    ]
